pipeline {
    agent any
    stages {
        stage('Build & Test') {
            steps {
                echo 'Running global checks...'
            }
        }
        stage('Deploy to Staging') {
            when {
                branch 'develop'
            }
            steps {
                echo 'Deploying to Staging environment...'
            }
        }
        stage('Release to Production') {
            when {
                branch 'main'
            }
            steps {
                echo 'Deploying to Production environment...'
            }
        }
    }
}
